name: FISOR
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_0
  - pip=23.2.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - bullet-safety-gym==1.4.0
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - chex==0.1.82
    - click==8.1.6
    - cloudpickle==2.2.1
    - colorama==0.4.6
    - commonmark==0.9.1
    - contextlib2==21.6.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - decorator==5.1.1
    - dm-control==1.0.14
    - dm-env==1.6
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - etils==1.4.1
    - exceptiongroup==1.1.2
    - farama-notifications==0.0.4
    - flax==0.5.3
    - fonttools==4.42.0
    - gast==0.5.4
    - gitdb==4.0.10
    - gitpython==3.1.32
    - glfw==2.6.2
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.28.1
    - h5py==3.9.0
    - idna==3.4
    - imageio==2.31.1
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - iniconfig==2.0.0
    - jax==0.4.9
    - jax-jumpy==1.0.0
    - jaxlib==0.4.9+cuda12.cudnn88
    - kiwisolver==1.4.4
    - labmaze==1.0.6
    - llvmlite==0.41.1
    - lxml==4.9.3
    - markdown-it-py==3.0.0
    - matplotlib==3.7.2
    - mdurl==0.1.2
    - metadrive-simulator==0.2.6.0
    - ml-collections==0.1.1
    - ml-dtypes==0.2.0
    - msgpack==1.0.5
    - mujoco==2.3.7
    - nest-asyncio==1.5.7
    - numba==0.58.1
    - numpy==1.25.2
    - nvidia-cublas-cu12==12.2.4.5
    - nvidia-cuda-cupti-cu12==12.2.131
    - nvidia-cuda-nvcc-cu12==12.2.128
    - nvidia-cuda-nvrtc-cu12==12.2.128
    - nvidia-cuda-runtime-cu12==12.2.128
    - nvidia-cudnn-cu12==8.9.4.25
    - nvidia-cufft-cu12==11.0.8.91
    - nvidia-cusolver-cu12==11.5.1.129
    - nvidia-cusparse-cu12==12.1.2.129
    - nvidia-nvjitlink-cu12==12.2.128
    - opencv-python-headless==4.8.0.76
    - opt-einsum==3.3.0
    - optax==0.1.5
    - orbax-checkpoint==0.3.2
    - packaging==23.1
    - panda3d==1.10.8
    - panda3d-gltf==1.0.0
    - panda3d-simplepbr==0.10
    - pandas==2.0.3
    - pathtools==0.1.2
    - pillow==10.0.0
    - platformdirs==3.10.0
    - pluggy==1.2.0
    - protobuf==3.20.1
    - psutil==5.9.5
    - pybullet==3.2.5
    - pycparser==2.21
    - pygame==2.1.0
    - pygments==2.16.1
    - pyopengl==3.1.7
    - pyparsing==3.0.9
    - pytest==7.4.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0.1
    - requests==2.31.0
    - rich==11.2.0
    - safety-gymnasium==0.4.0
    - scipy==1.11.1
    - seaborn==0.12.2
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - setuptools==64.0.3
    - six==1.16.0
    - smmap==5.0.0
    - tensorboardx==2.6.2.2
    - tensorflow-probability==0.21.0
    - tensorstore==0.1.41
    - tomli==2.0.1
    - toolz==0.12.0
    - tqdm==4.66.1
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - urllib3==2.0.4
    - wandb==0.15.8
    - xmltodict==0.13.0
    - yapf==0.40.1
    - zipp==3.16.2
prefix: /home/air-rl/anaconda3/envs/FISOR
